[package]
name = "cpcsp"
description = "Safe Rust wrapper for CryptoPro CSP 5.0"
version.workspace = true
edition.workspace = true
license.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
cpcsp-ffi-linux = { path = "../cpcsp-ffi-linux" }

[dependencies]
thiserror = "2"
zeroize = "1"

[dev-dependencies]
hex = "0.4"

[target.'cfg(target_os = "windows")'.dependencies]
cpcsp-ffi-windows = { path = "../cpcsp-ffi-windows" }
