[workspace]
resolver = "2"
members = [
    "crates/cpcsp",
    "crates/cpcsp-ffi-linux",
]
exclude = [
    "crates/cpcsp-ffi-windows",
]

[workspace.package]
version = "0.2.3"
edition = "2021"
license = "MIT OR Apache-2.0"
authors  = ["Mikhail Alekseev <298373@gmail.com>"]
repository = "https://github.com/mamon-t/cpcsp-rs"
