[workspace]
resolver = "2"
members = [
    "crates/cpcsp",
    "crates/cpcsp-ffi-linux",
    "crates/cpcsp-ffi-windows",
]

[workspace.package]
version = "0.2.1"
edition = "2021"
license = "BSD-2-Clause"
authors  = ["Mikhail Alekseev <298373@gmail.com>"]
repository = "https://github.com/mamon-t/cpcsp-rs"
