[package]
name = "cpcsp-ffi-linux"
description = "Raw FFI bindings for CryptoPro CSP 5.0 on Linux"
version = "0.2.1"
edition. = "2021"
authors  = ["Mikhail Alekseev <298373@gmail.com>"]
repository = "https://github.com/mamon-t/cpcsp-rs"

[dependencies]
libc = "0.2"

[dev-dependencies]
memoffset = "0.9"
